"use client";

import {useMemo, useState} from "react";
import {Activity,Archive,BadgeCheck,BarChart3,Box,Braces,Clock,Compass,FileText,FlaskConical,GitBranch,Grid3X3,Image,Landmark,Layers3,LineChart,Link2,ListRestart,Map,MapPin,Microscope,Network,Newspaper,PanelsTopLeft,PenLine,Quote,RefreshCw,Route,ScanLine,ScanSearch,Search,SearchCheck,Send,ShieldCheck,Shuffle,Tags,Waypoints,Workflow} from "lucide-react";

type AppEntry = {title:string; category:string; focus:string; goal:string; problem:string; description:string; url:string};

const categories=["All","AI Visibility","E-E-A-T & Trust","Citations & Answers","Content Strategy","Content Creation","Entity & Schema","NLP & Entity Analysis","SERP Intelligence","Search Analytics","SEO Intelligence","Technical SEO","Local SEO","Travel"];

const appIcons:Record<string,typeof Search>={
  "Search & LLM Citations Research Platform":Search,
  "AI Visibility Auditor Pro":ScanSearch,
  "LLM Citation Tracker":Quote,
  "AI Answer Change Monitor":Activity,
  "AI Citation Experiment Lab":FlaskConical,
  "AI Citation Reverse Engineering":GitBranch,
  "AI Hallucination & Brand Fact Checker":ShieldCheck,
  "Query Fan-out Explorer":Network,
  "Topical Authority Mapping & Entity SEO Diagnostics Engine":Map,
  "Topical Map & Content Gap Analysis":Grid3X3,
  "Site Content Architecture & Gap Auditor":Workflow,
  "Entity SEO & Internal Linking Platform":Link2,
  "Evidence-Led Content Brief & Outline Builder":FileText,
  "First-Hand Experience & Information-Gain Miner":Microscope,
  "Expert Quote & Evidence Vault":Archive,
  "IG-Elevator: RAG-Ready Content Architect":Layers3,
  "AI SEO Blog Refresh Engine":RefreshCw,
  "Bulk AI SEO Blog Refresh Engine":ListRestart,
  "Blog Content Rewriter":PenLine,
  "Attraction Content Writer":Landmark,
  "Content Decay & Fact Expiry Radar":Clock,
  "Lumina NER Engine":ScanLine,
  "Named Entity Recognition, Salience, Sentiment & N-Gram Collocation Engine":Tags,
  "Schema & Entity Markup Auditor":Braces,
  "Search Quality Rater Pro":BadgeCheck,
  "SERP Intelligence Analyst":SearchCheck,
  "SERP Layout GEO Citation Analyzer":PanelsTopLeft,
  "Search Intent Drift Detector":Shuffle,
  "SEMrush Position Analysis":LineChart,
  "GSC SEO Dashboard":BarChart3,
  "SEO Morning Brief":Newspaper,
  "Sitemap Auditor":Waypoints,
  "Indexing & Publishing Control Centre":Send,
  "Visual Search & Multimodal SEO Auditor":Image,
  "GBP Audit Pro":MapPin,
  "Travel Blueprint":Compass,
  "Travel Itinerary Planner":Route,
};

function AppSymbol({title}:{title:string}){const Icon=appIcons[title]||Box;return <Icon size={25} strokeWidth={1.8}/>}

const apps:AppEntry[]=[
{title:"Search & LLM Citations Research Platform",category:"AI Visibility",focus:"AI-search readiness",goal:"Measure how clearly AI search systems can understand, retrieve, cite, and surface a brand.",problem:"Brands often cannot diagnose why they are absent from AI-generated answers and citations.",description:"Researches brand entities, content structure, authority signals, retrieval readiness, and citation opportunities across leading generative-search platforms.",url:"https://seogirl-ai-visibility-auditor.vercel.app/"},
{title:"AI Visibility Auditor Pro",category:"E-E-A-T & Trust",focus:"Strategic audit",goal:"Turn AI-search readiness analysis into a prioritized improvement plan.",problem:"Traditional SEO audits do not fully explain whether AI systems can understand, trust, and cite a brand.",description:"Evaluates brand understanding, entity strength, content retrievability, and citation readiness across major AI platforms.",url:"https://seogirl-ai-visibility-auditor-pro.vercel.app/"},
{title:"LLM Citation Tracker",category:"Citations & Answers",focus:"Citation tracking",goal:"Track where a brand is mentioned and cited across leading AI platforms.",problem:"AI citations are fragmented across platforms, making visibility and competitor gaps hard to monitor.",description:"Tracks brand citations, source domains, competitor coverage, and content opportunities across major LLMs.",url:"https://seogirl-llm-citation-tracker.vercel.app/"},
{title:"AI Answer Change Monitor",category:"Citations & Answers",focus:"Answer monitoring",goal:"Detect meaningful changes in AI answers, citations, and brand visibility over time.",problem:"Teams cannot easily tell when a brand disappears, a citation is lost, or a competitor enters an AI answer.",description:"Preserves answer snapshots and flags brand losses, citation changes, new domains, and material response shifts.",url:"https://seogirl-ai-answer-change-monitor.vercel.app/"},
{title:"AI Citation Experiment Lab",category:"Citations & Answers",focus:"Controlled testing",goal:"Measure whether a controlled content change is associated with improved AI citation visibility.",problem:"Before-and-after AI citation tests are often inconsistent, incomplete, or interpreted without enough evidence.",description:"Structures experiments using fixed queries, control and treatment observations, citation rates, and confidence checks.",url:"https://seogirl-ai-citation-experiment-lab.vercel.app/"},
{title:"AI Citation Reverse Engineering",category:"Citations & Answers",focus:"Retrieval journeys",goal:"Explain how AI systems move from a question to searches, sources, citations, and recommendations.",problem:"Marketers can see an AI answer but not the retrieval journey or source patterns behind it.",description:"Maps prompt fan-out, retrieved sources, cited pages, and brand recommendations to reveal actionable patterns.",url:"https://seogirl-ai-citation-reverse-engineering.vercel.app/"},
{title:"AI Hallucination & Brand Fact Checker",category:"Citations & Answers",focus:"Brand accuracy",goal:"Verify AI-generated brand claims against an approved source of truth.",problem:"AI answers can repeat inaccurate, outdated, or unsupported information about a brand.",description:"Checks captured AI answers against a governed fact base and preserves findings for human review.",url:"https://seogirl-ai-hallucination-brand-fact-checker.vercel.app/"},
{title:"Query Fan-out Explorer",category:"Citations & Answers",focus:"Query expansion",goal:"Show how a broad question expands into the searches and subtopics needed to answer it.",problem:"A single keyword rarely reveals the full set of intents, entities, and evidence required for AI coverage.",description:"Expands questions into related queries, subtopics, entities, and content opportunities.",url:"https://seogirl-query-fanout-ai-coverage-auditor.vercel.app/"},
{title:"Topical Authority Mapping & Entity SEO Diagnostics Engine",category:"Content Strategy",focus:"Semantic architecture",goal:"Turn a website’s content inventory into a coherent semantic growth plan.",problem:"Sites often contain disconnected pages, weak clusters, missing entities, and underused internal links.",description:"Maps pillars and clusters, identifies semantic gaps, and recommends internal links and a content roadmap.",url:"https://seogirl-semantic-content-mapper.vercel.app/"},
{title:"Topical Map & Content Gap Analysis",category:"Content Strategy",focus:"Topical mapping",goal:"Build a structured, intent-led topical map from market and competitor evidence.",problem:"Keyword lists do not show how topics should be grouped, prioritized, or connected.",description:"Discovers keywords, clusters them by intent, analyzes coverage, and generates a structured topical map.",url:"https://seogirl-topical-map-content-gap-brand-neutr.vercel.app/"},
{title:"Site Content Architecture & Gap Auditor",category:"Content Strategy",focus:"Architecture gaps",goal:"Identify missing content types, topic clusters, and linking pathways across a site.",problem:"Teams struggle to compare existing architecture with competitor coverage and user needs.",description:"Maps pages and blog content, compares competitive coverage, and surfaces structural and linking gaps.",url:"https://seogirl-site-content-architecture-gap-audit.vercel.app/"},
{title:"Entity SEO & Internal Linking Platform",category:"Content Strategy",focus:"Entity-led linking",goal:"Create evidence-led entity relationships, schema recommendations, and meaningful internal links.",problem:"Recommendations are often made without verifying page evidence, identity, ownership, or user value.",description:"Maps entities and owner pages, audits links and JSON-LD, and produces reviewable recommendations.",url:"https://seogirl-entity-seo-internal-linking-platfor.vercel.app/"},
{title:"Evidence-Led Content Brief & Outline Builder",category:"Content Strategy",focus:"Content briefing",goal:"Convert research findings into a practical, defensible writing plan.",problem:"Content briefs often rely on generic headings instead of real gaps, journeys, and evidence.",description:"Combines content gaps, query fan-out, competitor research, and citation evidence into actionable outlines.",url:"https://seogirl-evidence-led-content-brief-outline.vercel.app/"},
{title:"First-Hand Experience & Information-Gain Miner",category:"Content Strategy",focus:"Original evidence",goal:"Transform generic drafts into distinctive content supported by real evidence.",problem:"Writers lack a safe process for finding, collecting, and verifying first-hand information.",description:"Creates originality audits, interview questions, fieldwork tasks, claim-risk checks, and editorial plans.",url:"https://seogirl-first-hand-information-gain-miner.vercel.app/"},
{title:"Expert Quote & Evidence Vault",category:"Content Strategy",focus:"Evidence governance",goal:"Make original expert evidence easy to govern, find, and reuse responsibly.",problem:"Quotes, observations, consent records, and first-party research are often scattered.",description:"Organizes quotes, source documents, first-party data, consent, expiry, and approved reuse.",url:"https://seogirl-expert-quote-evidence-vault.vercel.app/"},
{title:"IG-Elevator: RAG-Ready Content Architect",category:"Content Strategy",focus:"Retrieval-ready content",goal:"Restructure content so retrieval systems can understand and reuse its strongest information.",problem:"Valuable facts are often buried in weak context, outdated claims, and dependent paragraphs.",description:"Finds stale facts and context gaps, then builds clear, self-contained, high-information passages.",url:"https://seogirl-ig-elevator-rag.vercel.app/"},
{title:"AI SEO Blog Refresh Engine",category:"Content Creation",focus:"Content refresh",goal:"Improve existing articles for semantic SEO, usefulness, and freshness.",problem:"Older content loses relevance as facts, intent, entities, and reader expectations change.",description:"Audits articles and produces stronger content for accuracy, coverage, readability, and search value.",url:"https://seogirl-ai-blog-refresh-engine.vercel.app/"},
{title:"Bulk AI SEO Blog Refresh Engine",category:"Content Creation",focus:"Bulk refreshing",goal:"Scale content-refresh analysis across many blog URLs.",problem:"Reviewing large content libraries page by page is slow and makes prioritization difficult.",description:"Crawls multiple URLs, evaluates refresh needs with AI, and organizes page-level SEO recommendations.",url:"https://seogirl-bulk-ai-seo-blog-refresh-engine.vercel.app/"},
{title:"Blog Content Rewriter",category:"Content Creation",focus:"Content rewriting",goal:"Modernize and expand articles without losing valuable source material.",problem:"Automated rewrites can remove links, images, facts, or the brand’s established style.",description:"Rewrites and expands articles while preserving important links, images, facts, and brand voice.",url:"https://seogirl-blog-content-rewriter.vercel.app/"},
{title:"Attraction Content Writer",category:"Content Creation",focus:"Destination copy",goal:"Produce consistent, research-informed attraction-page copy at scale.",problem:"Destination teams need quality attraction content without sacrificing factual checks or consistency.",description:"Researches and generates attraction copy with quality controls, batch processing, and export-ready outputs.",url:"https://seogirl-attraction-content-writer.vercel.app/"},
{title:"Content Decay & Fact Expiry Radar",category:"Content Creation",focus:"Content freshness",goal:"Prevent time-sensitive facts from quietly becoming outdated.",problem:"Prices, schedules, policies, statistics, and other expiring claims are difficult to govern at scale.",description:"Extracts time-sensitive claims, records sources and review windows, and supports human review.",url:"https://seogirl-content-decay-fact-expiry-radar.vercel.app/"},
{title:"Lumina NER Engine",category:"NLP & Entity Analysis",focus:"Named entities",goal:"Make the entities inside a piece of content visible and understandable.",problem:"Teams cannot easily see which people, places, organizations, and concepts a text communicates.",description:"Uses AI-powered named entity recognition to identify, classify, and visualize entities.",url:"https://seogirl-lumina-ner-engine.vercel.app/"},
{title:"Named Entity Recognition, Salience, Sentiment & N-Gram Collocation Engine",category:"NLP & Entity Analysis",focus:"Language analysis",goal:"Provide a practical workspace for examining the language, entities, and phrase relationships within content.",problem:"Entity salience, sentiment, NER processing, and phrase frequency are spread across separate tools.",description:"Combines named entity recognition, salience, sentiment, NER visualization, and n-gram collocation analysis in one workspace.",url:"https://seogirl-natural-language-inspector.vercel.app/"},
{title:"Schema & Entity Markup Auditor",category:"Entity & Schema",focus:"Structured data",goal:"Validate page-level structured data and recommend safer connected markup.",problem:"Schema often contains missing requirements, disconnected entities, or unsupported assumptions.",description:"Extracts visible signals and JSON-LD, identifies issues, and produces evidence-first recommendations.",url:"https://seogirl-schema-entity-markup-auditor.vercel.app/"},
{title:"Search Quality Rater Pro",category:"E-E-A-T & Trust",focus:"Page quality",goal:"Evaluate page quality using a systematic search-quality framework.",problem:"SEO reviews often overlook trust, purpose, YMYL risk, spam policies, and user satisfaction.",description:"Audits quality criteria, E-E-A-T and trust, YMYL considerations, spam risks, and Needs Met.",url:"https://seogirl-search-quality-rater-pro.vercel.app/"},
{title:"SERP Intelligence Analyst",category:"SERP Intelligence",focus:"Live SERP analysis",goal:"Turn live search results into an evidence-based competitive search strategy.",problem:"Rankings, AI Overviews, citations, intent, and competitor movement are hard to analyze together.",description:"Analyzes organic rankings, AI Overviews, citations, page types, intent, competitors, and opportunities.",url:"https://seogirl-serp-intelligence-analyst.vercel.app/"},
{title:"SERP Layout GEO Citation Analyzer",category:"SERP Intelligence",focus:"SERP quality & GEO",goal:"Evaluate result composition through search-quality and generative-search lenses.",problem:"Conventional SERP reviews may miss page-quality signals and AI citation characteristics.",description:"Analyzes SERP layouts using search-quality principles, language signals, and GEO criteria.",url:"https://seogirl-serp-layout-geo-citation-analyzer.vercel.app/"},
{title:"Search Intent Drift Detector",category:"SERP Intelligence",focus:"Intent change",goal:"Detect when the meaning and result composition of a query begins to change.",problem:"Teams can mistake intent-driven ranking movement for a simple page-performance issue.",description:"Compares controlled SERP snapshots to identify changes in intent, result types, and competitors.",url:"https://seogirl-search-intent-drift-detector.vercel.app/"},
{title:"SEMrush Position Analysis",category:"Search Analytics",focus:"Rank tracking",goal:"Convert position-tracking data into clear ranking and competitive insights.",problem:"Large SEMrush exports make meaningful keyword movement and visibility gaps difficult to see.",description:"Tracks ranking changes, competitor visibility, and opportunities from SEMrush position data.",url:"https://seogirl-semrush-position-analysis.vercel.app/"},
{title:"GSC SEO Dashboard",category:"Search Analytics",focus:"GSC reporting",goal:"Make Google Search Console performance data easier to classify and act on.",problem:"Raw GSC exports do not explain which page types or site sections drive performance.",description:"Classifies URLs with a priority taxonomy and turns GSC metrics into actionable category views.",url:"https://seogirl-seo-dashboard.vercel.app/"},
{title:"SEO Morning Brief",category:"SEO Intelligence",focus:"Industry monitoring",goal:"Deliver a concise daily briefing on developments that matter to senior SEO practitioners.",problem:"Important Google updates, patents, research, and expert commentary are scattered and uneven.",description:"Monitors authoritative sources, scores developments, and produces searchable executive briefings.",url:"https://seogirl-seo-morning-brief-vercel.vercel.app/"},
{title:"Sitemap Auditor",category:"Technical SEO",focus:"Sitemap coverage",goal:"Verify that crawlable pages, sitemaps, and URL taxonomy align.",problem:"Important URLs can be missing, misclassified, or disconnected from the internal crawl structure.",description:"Crawls pages, parses XML sitemaps, applies taxonomy rules, and surfaces coverage issues.",url:"https://seogirl-sitemap-auditor.vercel.app/"},
{title:"Indexing & Publishing Control Centre",category:"Technical SEO",focus:"Indexing workflow",goal:"Provide a safer technical preflight and submission workflow for updated URLs.",problem:"Teams submit pages without checking indexing blockers or preserving a submission record.",description:"Inspects URL readiness, highlights indexing risks, and supports controlled IndexNow submission.",url:"https://seogirl-indexing-publishing-control-centre.vercel.app/"},
{title:"Visual Search & Multimodal SEO Auditor",category:"Technical SEO",focus:"Image SEO",goal:"Improve how images are described, connected, and discovered in search.",problem:"Image SEO issues span accessibility, context, structured data, duplication, and originality.",description:"Audits image metadata, HTML attributes, nearby text, structured data, and duplicate signals.",url:"https://seogirl-visual-search-multimodal-seo-audit.vercel.app/"},
{title:"GBP Audit Pro",category:"Local SEO",focus:"Google Business Profile",goal:"Improve the completeness, credibility, and local-search performance of Google Business Profiles.",problem:"Businesses miss profile fields, trust signals, content opportunities, and local SEO improvements.",description:"Identifies GBP optimization gaps and provides prioritized recommendations for local visibility.",url:"https://seogirl-gbp-audit-pro.vercel.app/"},
{title:"Travel Blueprint",category:"Travel",focus:"Destination guides",goal:"Turn destination research into a practical, complete travel-planning guide.",problem:"Travellers piece together itineraries, neighbourhoods, dining, and transit from disconnected sources.",description:"Generates destination guides with itineraries, stay selectors, dining guidance, and transit planning.",url:"https://seogirl-authority-travel-guides.vercel.app/"},
{title:"Travel Itinerary Planner",category:"Travel",focus:"Trip planning",goal:"Create personalized itineraries that are current and geographically efficient.",problem:"Generic plans often ignore location, timing, route order, and up-to-date information.",description:"Builds personalized, geographically optimized itineraries using live web-grounded research.",url:"https://seogirl-travel-itinerary-planner.vercel.app/"},
];

export default function AppLibrary(){
  const[active,setActive]=useState("All");const[expanded,setExpanded]=useState(false);
  const shown=useMemo(()=>apps.filter(app=>active==="All"||app.category===active),[active]);
  const isFiltered=active!=="All";const visibleApps=isFiltered||expanded?shown:shown.slice(0,9);
  return <section className="appLibrary wrap" id="library"><div className="libraryTools"><div className="filters" aria-label="Filter by category">{categories.map(category=><button className={active===category?"active":""} onClick={()=>setActive(category)} key={category}>{category}</button>)}</div></div><div className="resultMeta"><span>{visibleApps.length===shown.length?`${shown.length} documented ${shown.length===1?"app":"apps"}`:`Showing ${visibleApps.length} of ${shown.length} documented apps`}</span><span>{apps.length} apps in the collection</span></div><div className="libraryGrid" id="app-library-grid">{visibleApps.map((app,index)=><article className="libraryCard" key={app.title}><div className="cardHead"><span>{String(index+1).padStart(2,"0")}</span><small className="live-build">Built app</small></div><div className="appIcon" aria-hidden="true"><AppSymbol title={app.title}/></div><span className="appCategory">{app.category} · {app.focus}</span><h2>{app.title}</h2><div className="appFunction"><span>What it does</span><p className="appDescription">{app.description}</p></div><dl className="appDetails"><div><dt>Outcome</dt><dd>{app.goal}</dd></div><div><dt>Why it matters</dt><dd>{app.problem}</dd></div></dl><div className="cardFoot"><a href={app.url} target="_blank" rel="noreferrer">Open app <b>↗</b></a></div></article>)}</div>{!isFiltered&&shown.length>9&&<div className="libraryExpand"><button onClick={()=>setExpanded(value=>!value)} aria-expanded={expanded} aria-controls="app-library-grid">{expanded?"Show fewer":`See all ${shown.length} apps`} <span aria-hidden="true">{expanded?"↑":"↓"}</span></button><p>{expanded?"Collapse the collection":"Explore the complete app library"}</p></div>}{shown.length===0&&<div className="empty"><h2>No tools found</h2><p>Choose another category.</p><button onClick={()=>setActive("All")}>Clear filters</button></div>}</section>;
}
