import Link from "next/link";
import {GraduationCap,Gamepad2,Rocket,Plane,ShoppingBag,BadgeCheck,FileSearch,TrendingUp,RotateCcw,Search,BrainCircuit,ListFilter,Hammer} from "lucide-react";
const featured=[
{code:"AI-01",title:"AI Citation Reverse Engineering",category:"AI Visibility",copy:"Trace how AI search moves from a user question to searches, sources, citations, and brand recommendations.",tags:["Query fan-out","Citations","AI retrieval"],accent:"violet",image:"/app-previews/ai-citation-reverse-engineering.png",url:"https://seogirl-ai-citation-reverse-engineering.vercel.app/"},
{code:"SR-02",title:"SERP Intelligence Analyst",category:"SERP Research",copy:"Turn live results, AI Overviews, citations, and competitor patterns into an evidence-based content strategy.",tags:["Live SERPs","AI Overviews","Intent"],accent:"blue",image:"/app-previews/serp-intelligence-analyst.png",url:"https://seogirl-serp-intelligence-analyst.vercel.app/"},
{code:"CS-03",title:"First-Hand Experience & Information-Gain Miner",category:"Content Systems",copy:"Turn generic drafts into original editorial plans built around interviews, fieldwork, measurements, and verifiable evidence.",tags:["Information gain","Evidence","Originality"],accent:"green",image:"/app-previews/information-gain-miner.png",url:"https://seogirl-first-hand-information-gain-miner.vercel.app/"},
{code:"TS-04",title:"Sitemap Auditor",category:"Technical SEO",copy:"Compare crawled pages, XML sitemaps, and URL taxonomy to expose missing, misclassified, and disconnected content at scale.",tags:["Crawling","Coverage","Taxonomy"],accent:"pink",image:"/app-previews/sitemap-auditor.png",url:"https://seogirl-sitemap-auditor.vercel.app/"}];
const caseStudies=[
{client:"ToursByLocals",title:"Enterprise marketplace SEO",result:"40K+ pages missing from sitemaps identified",copy:"Audited sitemap and crawl coverage, surfaced large-scale discovery gaps, improved LCP, and developed entity-led descriptions for tours, attractions, destinations, and guide-led experiences.",tags:["Technical SEO","Entity content","Core Web Vitals"]},
{client:"LegalUSPokerSites",title:"Post-update recovery & entity authority",result:"90% organic traffic recovered in 8 to 10 weeks",copy:"Combined technical remediation, semantic content improvements, entity schema, authorship, and cross-platform brand consistency to rebuild search and AI visibility.",tags:["Recovery","Entity SEO","AI citations"]},
{client:"Concordia Shanghai",title:"Content-led organic growth",result:"214% YoY growth in blog clicks",copy:"Built an intent-led content roadmap, refreshed high-value pages, improved conversion paths, and aligned content with parent questions and admissions goals.",tags:["Content strategy","Featured snippets","CRO"]},
{client:"International School Bangkok",title:"Persona-led admissions growth",result:"50%+ of goal completions from organic search",copy:"Created a Japanese-parent persona, pillar strategy, localized content journey, and measurement framework that connected search visibility to admissions outcomes.",tags:["Persona strategy","Multilingual SEO","Lead generation"]},
{client:"International School of Beijing",title:"Technical SEO & migration",result:"58% reduction in broken links",copy:"Protected search equity through domain migrations, repaired technical issues, developed pillar pages, strengthened internal linking, and improved the admissions journey.",tags:["Migration","Technical SEO","Content architecture"]}];
const systems=[
"Merge-and-purge content playbook","Authorship and E-E-A-T guidelines","Entity and schema implementation guide","Semantic keyword and n-gram research framework","Brand consistency guidelines","SEO configuration and QA checklists"];
export default function Home(){return <main>
<header className="nav wrap"><Link className="logo" href="/">SEO<span>Girl</span></Link><nav><a href="#work">Selected Work</a><Link href="/apps">Tools</Link><Link href="/blog">Insights</Link><a href="#approach">Approach</a><Link href="/about">About</Link></nav></header>
<section className="hero wrap"><div className="status"><i/> SEO STRATEGY × AI PRODUCT THINKING</div><h1>Where AI meets search,<br/><span>I make brands visible.</span></h1><p className="heroCopy">I’m Ami, an SEO Strategist who connects technical SEO, content systems, AI visibility, and product thinking. I turn complex analysis into focused strategies and practical tools teams can actually use.</p><div className="heroActions"><a className="primary" href="#work">View selected work</a><a className="secondary" href="mailto:hello@seogirl.ca">Let’s talk</a></div></section>
<section className="industries wrap" aria-labelledby="industries-title"><div className="industriesIntro"><span className="mini">INDUSTRY EXPERIENCE</span><h2 id="industries-title">SEO across complex<br/>markets.</h2></div><div className="industryGrid">{([["International Schools",GraduationCap],["iGaming",Gamepad2],["Startups",Rocket],["Travel & Tourism",Plane],["E-commerce",ShoppingBag]] as const).map(([industry,Icon],index)=><div key={String(industry)}><span>{String(index+1).padStart(2,"0")}</span><i aria-hidden="true"><Icon size={25} strokeWidth={1.8}/></i><strong>{industry}</strong></div>)}</div></section>
<section className="featured wrap" id="work"><div className="sectionIntro"><div><span className="mini">SELECTED BUILDS</span><h2>SEO methodology,<br/>made usable.</h2></div><div><p>These are not tools built for the sake of AI. Each one starts with a recurring search problem and turns my strategic process into a simpler decision system.</p><Link href="/apps">Browse all apps <b>↗</b></Link></div></div><div className="featuredGrid">{featured.map(app=><article className={`productCard ${app.accent}`} key={app.title}><div className="productTop"><span>{app.code}</span><span>{app.category}</span></div><a className="productVisual appPreview" href={app.url} target="_blank" rel="noreferrer" aria-label={`Open ${app.title}`}><img src={app.image} alt={`${app.title} interface preview`}/></a><h3>{app.title}</h3><p>{app.copy}</p><ul>{app.tags.map(tag=><li key={tag}>{tag}</li>)}</ul><a href={app.url} target="_blank" rel="noreferrer" aria-label={`Open ${app.title}`}>Open app <b>↗</b></a></article>)}</div></section>
<section className="caseStudySection" id="experience"><div className="wrap"><div className="sectionIntro"><div><span className="mini">SELECTED EXPERIENCE</span><h2>Strategy measured<br/>in outcomes.</h2></div><div><p>Search growth is rarely one isolated fix. These projects connect technical SEO, content architecture, entity clarity, user experience, and measurement to business outcomes.</p></div></div><div className="caseStudyGrid">{caseStudies.map((study,index)=><article className={index===0?"caseStudyCard featuredCase":"caseStudyCard"} key={study.client}><div className="caseMeta"><span>{String(index+1).padStart(2,"0")}</span><span>{study.client}</span></div><h3>{study.title}</h3><strong>{study.result}</strong><p>{study.copy}</p><ul>{study.tags.map(tag=><li key={tag}>{tag}</li>)}</ul></article>)}</div></div></section>
<section className="impactStats wrap" aria-label="Selected SEO results">{([["9+","Years in SEO",BadgeCheck],["40K+","Sitemap gaps identified",FileSearch],["214%","YoY blog click growth",TrendingUp],["90%","Traffic recovered",RotateCcw]] as const).map(([value,label,Icon])=><div key={String(label)}><b>{value}</b><i aria-hidden="true"><Icon size={24} strokeWidth={1.8}/></i><span>{label}</span></div>)}</section>
<section className="libraryBand"><div className="wrap libraryInner"><div><span className="mini">THE APP LIBRARY</span><h2>One body of work.<br/><em>Thirteen problem spaces.</em></h2><p>The live collection brings together 37 apps across AI visibility, E-E-A-T, NLP, citations, content systems, entity SEO, SERP research, search analytics, technical SEO, local search, and travel planning.</p><Link className="lightButton" href="/apps">Open the library <b>↗</b></Link></div><div className="categoryStack">{[["01","AI Visibility","1 app"],["02","E-E-A-T & Trust","2 apps"],["03","Citations & Answers","6 apps"],["04","Content Strategy","8 apps"],["05","Content Creation","5 apps"],["06","Entity & Schema","1 app"],["07","NLP & Entity Analysis","2 apps"],["08","SERP Intelligence","3 apps"],["09","Search Analytics","2 apps"],["10","SEO Intelligence","1 app"],["11","Technical SEO","3 apps"],["12","Local SEO","1 app"],["13","Travel","2 apps"]].map(row=><div key={row[0]}><span>{row[0]}</span><strong>{row[1]}</strong><small>{row[2]}</small></div>)}</div></div></section>
<section className="method wrap" id="approach"><span className="mini">HOW I BUILD</span><div className="methodHeader"><h2>From a messy SEO problem<br/>to a focused product.</h2><p>My apps make the strategic reasoning visible; not just the final output.</p></div><div className="steps">{[{number:"01",title:"Diagnose",copy:"Define the real decision the user is struggling to make.",Icon:Search},{number:"02",title:"Model",copy:"Turn SEO knowledge into evidence, rules, and a repeatable methodology.",Icon:BrainCircuit},{number:"03",title:"Simplify",copy:"Remove metrics and steps that do not change the next action.",Icon:ListFilter},{number:"04",title:"Build & test",copy:"Create a usable workflow, test its outputs, and refine the logic.",Icon:Hammer}].map(({number,title,copy,Icon})=><div key={number}><span>{number}</span><i aria-hidden="true"><Icon size={25} strokeWidth={1.8}/></i><h3>{title}</h3><p>{copy}</p></div>)}</div></section>
<section className="systems wrap"><div><span className="mini">SYSTEMS & PLAYBOOKS</span><h2>Reusable knowledge,<br/>not one-off advice.</h2><p>I turn working SEO methods into clear standards that content, product, marketing, and development teams can apply consistently.</p></div><div className="systemList">{systems.map((system,index)=><div key={system}><span>{String(index+1).padStart(2,"0")}</span><strong>{system}</strong></div>)}</div></section>
<section className="about wrap" id="about"><div><span className="mini">ABOUT AMI</span><h2>Strategy is strongest when people can use it.</h2></div><div><p>I’m an SEO Strategist with more than nine years of experience and a background in computer science, IT management, e-commerce, and international marketing. I work across technical SEO, site migrations, information architecture, content strategy, entity SEO, Core Web Vitals, and emerging AI visibility.</p><p>At ToursByLocals, my work includes diagnosing enterprise-scale sitemap coverage, improving LCP, building entity-led descriptions for tours and attractions, analyzing search performance, and translating technical findings into priorities that content, product, and development teams can implement.</p><p>What ties the work together is a systems mindset: finding the real constraint, connecting evidence across disciplines, and turning the answer into something clear enough to act on.</p><Link href="/about">Read my story <b>↗</b></Link></div></section>
<footer><div className="wrap"><div><span className="mini">AMI SAEEDNIA · SEO STRATEGIST</span><h2>Let’s build something<br/>search can understand.</h2></div><div className="footerLinks"><a href="mailto:ameneh.saeednia@gmail.com">ameneh.saeednia@gmail.com ↗</a><a href="https://www.linkedin.com/in/ameneh-saeednia/" target="_blank" rel="noreferrer">LinkedIn ↗</a><Link href="/apps">App library ↗</Link></div></div></footer>
</main>}
